### GET request to example server
POST https://opensource-demo.orangehrmlive.com/web/index.php/auth/validate
Content-Type: application/json

{
    "username": "admin",
    "password": "admin123"
}

> {% client.global.set("token", response.body.token)
    console.log("Saved token:", client.global.get("token"))%}
###